sudo: required

services:
  - docker

language: java

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}

jobs:
  include:
    - stage: build docker image
      script:
      - ./gradlew clean build bootJar
      - export REPO=$(echo ${TRAVIS_REPO_SLUG} | cut -d"/" -f2)
      - export DOCKER_REPO="ibmmanagedsecurity/$REPO"
      - docker login -u="$DOCKER_USER" -p="$DOCKER_PASSWORD"
      - docker build -t $DOCKER_REPO:$TRAVIS_BRANCH .
      - docker tag $DOCKER_REPO:$TRAVIS_BRANCH $DOCKER_REPO:latest
      - docker images
      - docker push $DOCKER_REPO:$TRAVIS_BRANCH
      - docker push $DOCKER_REPO:latest
      if: tag =~ ^v[0-9]
      on:
        tags: true
