spring:
  cloud:
    config:
      server:
        git:
          force_pull: true
          uri: file:/opt/configserver
          searchPaths:
            - config-store/**
        prefix: cfg

management:
    security:
      enabled: false
