spring:
  cloud:
    config:
      server:
        git:
          force_pull: true
          uri: file:/opt/config-repo
          searchPaths:
            - config-store/**
          clone-on-start: true
        prefix: cfg
        bootstrap: true
        health:
          enabled: false


#server.port: 8080

management:
    security:
      enabled: false
